- name: sampleplay
  remote_user: devops
  hosts: localhost
  tasks:
  - shell: hostname
    register: up
  - debug:
      #var: up
      msg: "{{up.stdout}}"
  - name: "pass to other play"
    set_stats:
      data:
        var1: "{{up.stdout}}"
 
      
