- name: sampleplay
  remote_user: devops
  hosts: localhost
  tasks:
  - shell: hostname
    register: up
  - debug:
      var: up
  '''- name: "Artifact URL of test results to Tower Workflows"
    set_stats:
      data:
        var1:  "{{up.raw_result.0}}"'''
      
