- name: sampleplay
  remote_user: devops
  hosts: localhost
  tasks:
  - shell: hostname
    register: up
  - name: pass the data
    set_stats:
      data:
        var1: "hello"
      
  - debug:
     var: up.stdout
